/*
 * Copyright (C) 2026 Multiverse Contributors
 *
 * This file is part of Multiverse.
 *
 * Multiverse is free software: you can redistribute it and/or modify
 * it under the terms of the GNU Affero General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * Multiverse is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
 * GNU Affero General Public License for more details.
 *
 * You should have received a copy of the GNU Affero General Public License
 * along with Multiverse. If not, see <https://www.gnu.org/licenses/>.
 */

/**
 * SDK code generator for @fluxer/bot_sdk.
 *
 * Reads fluxer_docs/api-reference/openapi.json (the committed, Phase 1.0-cleaned
 * spec — its `security` metadata is derived, not asserted) and emits:
 *
 *   - src/types/Api.generated.tsx      — TypeScript types for every schema in
 *     components.schemas (all types are generated, even for endpoints bots
 *     cannot call, because gateway payloads and shared shapes reference them).
 *   - src/rest/Endpoints.generated.tsx — operationId → {method, path, params}
 *     for the bot-callable set only: operations whose `security` includes
 *     `botToken`.
 *
 * Everything with judgement in it (transport, auth, rate limiting, gateway
 * lifecycle) is hand-written; the generator's job is types and paths, nothing
 * else. Do not hand-edit the .generated.tsx outputs — fix this script or the
 * spec instead.
 *
 * Usage:
 *   pnpm --filter @fluxer/bot_sdk generate          # rewrite generated files
 *   pnpm --filter @fluxer/bot_sdk generate --check  # drift check (wired into lint)
 */

import {spawnSync} from 'node:child_process';
import fs from 'node:fs';
import path from 'node:path';
import {fileURLToPath} from 'node:url';

const __dirname = path.dirname(fileURLToPath(import.meta.url));
const REPO_ROOT = path.resolve(__dirname, '../../..');
const SPEC_PATH = path.join(REPO_ROOT, 'fluxer_docs/api-reference/openapi.json');
const TYPES_OUT = path.resolve(__dirname, '../src/types/Api.generated.tsx');
const ENDPOINTS_OUT = path.resolve(__dirname, '../src/rest/Endpoints.generated.tsx');

const LICENSE_HEADER = `/*
 * Copyright (C) 2026 Multiverse Contributors
 *
 * This file is part of Multiverse.
 *
 * Multiverse is free software: you can redistribute it and/or modify
 * it under the terms of the GNU Affero General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * Multiverse is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
 * GNU Affero General Public License for more details.
 *
 * You should have received a copy of the GNU Affero General Public License
 * along with Multiverse. If not, see <https://www.gnu.org/licenses/>.
 */
`;

const GENERATED_BANNER = `// Generated by packages/bot_sdk/scripts/GenerateSdk.tsx from
// fluxer_docs/api-reference/openapi.json. Do not edit by hand — regenerate with
// \`pnpm --filter @fluxer/bot_sdk generate\`.
`;

interface JsonSchema {
	$ref?: string;
	type?: string;
	enum?: Array<string | number>;
	anyOf?: Array<JsonSchema>;
	oneOf?: Array<JsonSchema>;
	items?: JsonSchema;
	properties?: Record<string, JsonSchema>;
	required?: Array<string>;
	additionalProperties?: JsonSchema | boolean;
	patternProperties?: Record<string, JsonSchema>;
	description?: string;
}

interface OpenApiOperation {
	operationId?: string;
	security?: Array<Record<string, Array<string>>>;
	parameters?: Array<{name: string; in: string; required?: boolean; schema?: JsonSchema}>;
	requestBody?: {content?: Record<string, {schema?: JsonSchema}>};
	responses?: Record<string, {content?: Record<string, {schema?: JsonSchema}>}>;
}

interface OpenApiSpec {
	paths: Record<string, Record<string, OpenApiOperation>>;
	components: {schemas: Record<string, JsonSchema>};
}

const HTTP_METHODS = ['get', 'post', 'put', 'patch', 'delete'] as const;
const IDENTIFIER_RE = /^[A-Za-z_$][A-Za-z0-9_$]*$/;

function refName(ref: string): string {
	const name = ref.split('/').at(-1);
	if (!name || !IDENTIFIER_RE.test(name)) {
		throw new Error(`Unsupported $ref: ${ref}`);
	}
	return name;
}

function quoteKey(key: string): string {
	return IDENTIFIER_RE.test(key) ? key : `'${key.replaceAll("'", "\\'")}'`;
}

function literalType(value: string | number): string {
	return typeof value === 'string' ? `'${value.replaceAll("'", "\\'")}'` : String(value);
}

function schemaToType(schema: JsonSchema | boolean | undefined, indent: string): string {
	if (schema === undefined || schema === true) return 'unknown';
	if (schema === false) return 'never';
	if (schema.$ref) return refName(schema.$ref);
	if (schema.enum) return schema.enum.map(literalType).join(' | ');
	const union = schema.anyOf ?? schema.oneOf;
	if (union) {
		if (union.length === 0) return 'never';
		const members = union.map((member) => schemaToType(member, indent));
		return members.length === 1 ? (members[0] as string) : members.join(' | ');
	}
	switch (schema.type) {
		case 'string':
			return 'string';
		case 'integer':
		case 'number':
			return 'number';
		case 'boolean':
			return 'boolean';
		case 'null':
			return 'null';
		case 'array':
			return `Array<${maybeParenthesize(schemaToType(schema.items, indent))}>`;
		case 'object':
			return objectSchemaToType(schema, indent);
		default:
			return 'unknown';
	}
}

function maybeParenthesize(type: string): string {
	return type.includes('|') || type.includes('&') ? `(${type})` : type;
}

function objectSchemaToType(schema: JsonSchema, indent: string): string {
	const parts: Array<string> = [];
	if (schema.properties && Object.keys(schema.properties).length > 0) {
		const required = new Set(schema.required ?? []);
		const inner = `${indent}\t`;
		const fields = Object.entries(schema.properties).map(([key, value]) => {
			const optional = required.has(key) ? '' : '?';
			return `${inner}${quoteKey(key)}${optional}: ${schemaToType(value, inner)};`;
		});
		parts.push(`{\n${fields.join('\n')}\n${indent}}`);
	}
	const record = schema.patternProperties
		? Object.values(schema.patternProperties)[0]
		: typeof schema.additionalProperties === 'object'
			? schema.additionalProperties
			: undefined;
	if (record) {
		parts.push(`Record<string, ${schemaToType(record, indent)}>`);
	}
	if (parts.length === 0) return 'Record<string, unknown>';
	return parts.join(' & ');
}

function generateTypes(spec: OpenApiSpec): string {
	const lines: Array<string> = [LICENSE_HEADER, GENERATED_BANNER];
	for (const [name, schema] of Object.entries(spec.components.schemas)) {
		if (!IDENTIFIER_RE.test(name)) {
			throw new Error(`Schema name is not a valid identifier: ${name}`);
		}
		lines.push(`export type ${name} = ${schemaToType(schema, '')};`);
	}
	return `${lines.join('\n')}\n`;
}

interface EndpointEntry {
	operationId: string;
	method: string;
	path: string;
	pathParams: Array<string>;
	queryParams: Array<string>;
	requestBodySchema: string | null;
	responseSchema: string | null;
}

function extractSchemaRef(content: Record<string, {schema?: JsonSchema}> | undefined): string | null {
	const schema = content?.['application/json']?.schema;
	return schema?.$ref ? refName(schema.$ref) : null;
}

function collectBotEndpoints(spec: OpenApiSpec): Array<EndpointEntry> {
	const entries: Array<EndpointEntry> = [];
	const seen = new Set<string>();
	for (const [pathTemplate, pathItem] of Object.entries(spec.paths)) {
		for (const method of HTTP_METHODS) {
			const op = pathItem[method];
			if (!op) continue;
			const security = op.security ?? [];
			const botCallable = security.some((requirement) => Object.hasOwn(requirement, 'botToken'));
			if (!botCallable) continue;
			if (!op.operationId) {
				throw new Error(`Missing operationId for ${method.toUpperCase()} ${pathTemplate}`);
			}
			if (seen.has(op.operationId)) {
				throw new Error(`Duplicate operationId: ${op.operationId}`);
			}
			seen.add(op.operationId);
			const parameters = op.parameters ?? [];
			const pathParams = parameters.filter((param) => param.in === 'path').map((param) => param.name);
			const queryParams = parameters.filter((param) => param.in === 'query').map((param) => param.name);
			const templateParams = [...pathTemplate.matchAll(/\{([^}]+)\}/g)].map((match) => match[1]);
			for (const templateParam of templateParams) {
				if (!pathParams.includes(templateParam as string)) {
					throw new Error(`Path param {${templateParam}} of ${pathTemplate} missing from parameters`);
				}
			}
			const successResponse =
				op.responses?.['200'] ?? op.responses?.['201'] ?? op.responses?.['202'] ?? op.responses?.['204'];
			entries.push({
				operationId: op.operationId,
				method: method.toUpperCase(),
				path: pathTemplate,
				pathParams,
				queryParams,
				requestBodySchema: extractSchemaRef(op.requestBody?.content),
				responseSchema: extractSchemaRef(successResponse?.content),
			});
		}
	}
	if (entries.length < 50) {
		throw new Error(
			`Only ${entries.length} bot-callable operations found — the spec looks wrong (expected ~100+). ` +
				'Refusing to generate from a suspicious spec.',
		);
	}
	entries.sort((a, b) => a.operationId.localeCompare(b.operationId));
	return entries;
}

function stringArrayLiteral(values: Array<string>): string {
	return `[${values.map((value) => `'${value}'`).join(', ')}]`;
}

function generateEndpoints(spec: OpenApiSpec): string {
	const entries = collectBotEndpoints(spec);
	const lines: Array<string> = [LICENSE_HEADER, GENERATED_BANNER];
	lines.push(`export type HttpMethod = 'GET' | 'POST' | 'PUT' | 'PATCH' | 'DELETE';`);
	lines.push('');
	lines.push('export interface BotEndpoint {');
	lines.push('\treadonly method: HttpMethod;');
	lines.push('\treadonly path: string;');
	lines.push('\treadonly pathParams: ReadonlyArray<string>;');
	lines.push('\treadonly queryParams: ReadonlyArray<string>;');
	lines.push('\treadonly requestBodySchema: string | null;');
	lines.push('\treadonly responseSchema: string | null;');
	lines.push('}');
	lines.push('');
	lines.push('/**');
	lines.push(' * Every operation the OpenAPI spec marks as callable with a bot token');
	lines.push(' * (`security` includes `botToken`). Operations restricted to user sessions');
	lines.push(' * are deliberately absent — the Phase 1.0 cleanup made this metadata');
	lines.push(' * trustworthy, and this map must never re-import the lie.');
	lines.push(' */');
	lines.push('export const BotEndpoints = {');
	for (const entry of entries) {
		lines.push(`\t${quoteKey(entry.operationId)}: {`);
		lines.push(`\t\tmethod: '${entry.method}',`);
		lines.push(`\t\tpath: '${entry.path}',`);
		lines.push(`\t\tpathParams: ${stringArrayLiteral(entry.pathParams)},`);
		lines.push(`\t\tqueryParams: ${stringArrayLiteral(entry.queryParams)},`);
		lines.push(`\t\trequestBodySchema: ${entry.requestBodySchema ? `'${entry.requestBodySchema}'` : 'null'},`);
		lines.push(`\t\tresponseSchema: ${entry.responseSchema ? `'${entry.responseSchema}'` : 'null'},`);
		lines.push('\t},');
	}
	lines.push('} as const satisfies Record<string, BotEndpoint>;');
	lines.push('');
	lines.push('export type BotOperationId = keyof typeof BotEndpoints;');
	return `${lines.join('\n')}\n`;
}

function biomeFormat(content: string, filePath: string): string {
	const result = spawnSync(
		path.join(REPO_ROOT, 'node_modules/.bin/biome'),
		['format', `--stdin-file-path=${filePath}`],
		{input: content, encoding: 'utf8', maxBuffer: 64 * 1024 * 1024},
	);
	if (result.status !== 0) {
		throw new Error(`biome format failed for ${filePath}: ${result.stderr}`);
	}
	return result.stdout;
}

function main(): void {
	const checkMode = process.argv.includes('--check');
	const spec = JSON.parse(fs.readFileSync(SPEC_PATH, 'utf8')) as OpenApiSpec;

	const outputs: Array<{filePath: string; content: string}> = [
		{filePath: TYPES_OUT, content: biomeFormat(generateTypes(spec), TYPES_OUT)},
		{filePath: ENDPOINTS_OUT, content: biomeFormat(generateEndpoints(spec), ENDPOINTS_OUT)},
	];

	let drifted = false;
	for (const {filePath, content} of outputs) {
		const relative = path.relative(REPO_ROOT, filePath);
		if (checkMode) {
			const existing = fs.existsSync(filePath) ? fs.readFileSync(filePath, 'utf8') : null;
			if (existing !== content) {
				drifted = true;
				console.error(`DRIFT: ${relative} is stale — run \`pnpm --filter @fluxer/bot_sdk generate\``);
			} else {
				console.log(`ok: ${relative}`);
			}
		} else {
			fs.writeFileSync(filePath, content);
			console.log(`wrote: ${relative}`);
		}
	}
	if (drifted) {
		process.exit(1);
	}
}

main();
